### ISSUE TITLE
Code for scraping document affiliation information hangs

### ISSUE THREAD

**Issue by sbenthall** [glasgow-ipl/ietfdata#114]
The following code hangs when ran locally:

https://gist.github.com/sbenthall/0c919094f6529b015015f9857e231ff5

This has been taking 10 minutes or so with no response.

Are we doing something wrong?

**Comment by csperkins** [comment]
I don't think you're doing anything wrong, but it does fetch the record for *every* internet-draft for a twelve month period. That's a lot to fetch, and likely takes some time.

Try setting the `IETFDATA_LOGLEVEL` environment variable to DEBUG and re-running in this sort of situation. This logs all interactions with the datatracker, so you can see if it's making progress.

**Comment by csperkins** [comment]
Also, and I think we spoke about this already, using `since` and `until` with documents probably doesn't do what you expect: it fetches documents where the metadata about the document was updated in that range, not documents that were submitted in that date range. Use `submissions()` with `date_since` and `date_until` to get documents submitted within a date range.

**Comment by sbenthall** [comment]
Thank you! That's all so helpful.

**Comment by csperkins** [comment]
BTW, your original code did eventually complete when I ran it – but it took a couple of hours to run. The stats reported in debug mode were:
```
DEBUG:ietfdata:cache requests: 8033
DEBUG:ietfdata:cache hit rate: 99.0%
DEBUG:ietfdata:HTTP GET calls: 2179
DEBUG:ietfdata:db requests: 49822
```
